---
title: "Arvore_de_decisao"
author: "Tiago Cruz"
date: "2025-04-24"
output: html_document
---

# Pacote
```{r}
library(rpart)
library(caret)
library(Amelia)
library(pROC)
library(rpart.plot)
library(tidyverse)
library(readr)
```


# funções Criadas
```{r}
DB_Treino_Teste <- function(semente, df, porc_train, porc_test){
  set.seed(semente)

  ind <- sample(2, nrow(df),
                replace = TRUE,
                prob = c(porc_train, porc_test))

  training <- df[ind==1,]
  testing <- df[ind==2,]

  return(list(Treino = training,
              Teste = testing))

}
```

# Banco de dados
```{r}
dados <- read_csv("https://raw.githubusercontent.com/Tiago-HCruz/Mapeamento_Cliques_Shop/refs/heads/main/Dados/Bd_Original_Comp.csv",
                  col_types = cols_only(`ID Sessão` = "c",
                                        Clique = "c",
                                        `País` = "c",
                                        `Categoria Principal` = "c",
                                        `Cor` = "c",
                                        `Localização` = "c",
                                        `Fotografia do Modelo` = "c",
                                        `Preço (US)` = "i",
                                        `Preço 2` = "c",
                                        `Página` = "c")) %>%
  rename(`ID_Sessao` = `ID Sessão`,
         Pais = `País`,
         `Categoria` = `Categoria Principal`,
         Localizacao = `Localização`,
         Fotografia_do_Modelo = `Fotografia do Modelo`,
         Preço = `Preço (US)`,
         Preco_2 = `Preço 2`,
         Pagina = Página
         )
dados
```

# analise resumida
```{r}
head(dados)         # Mostra as primeiras linhas
str(dados)          # Estrutura das variáveis (inclusive fatores)
summary(dados)   
```

# banco de dados treino e teste
```{r}
DB_T <- DB_Treino_Teste(2025, dados, 0.7, 0.3)
DB_T$Teste
```

```{r}
set.seed(2025)
ctrl <- trainControl(method = "cv",
                     number = 10,
                     summaryFunction = twoClassSummary,
                     classProbs = T)


dtFit <- train(Preco_2 ~ Pais + Categoria + Cor + Localizacao + Fotografia_do_Modelo + Preço + Pagina,
               method = "rpart2", #
               tuneLength = 20,
               trControl = ctrl,
               metric = "ROC",
               data = DB_T$Treino
               )

```

```{r}
plot(dtFit, main = NULL, bg = "#454141", col = "#E47C3D", pch = 0, cex = 1, lwd=2)
View()
```

```{r}
library(rpart.plot)
rpart.plot(dtFit$finalModel,
           extra = 101, #4
           type = 3, 
           #box.palette = "#E47C3D",
           tweak = 1.1,
           box.palette = c("#E47C3D", "#847C7C"),
#"RdYlGn", # display.brewer.pal(n=3, name= 'Reds'), #"YlOrBr"
           main = "Clique de usuários em um produto\n (Valor acima ou a média do mercado)"
           ,clip.right.labs = FALSE
           )
```




# Predição do modelo
```{r}
preddt <- predict(dtFit, 
                  dtFit$trainingData,
                  type = "prob")
resultado <- as.factor(ifelse(preddt[,2] > 0.5 , "ACIMA", "MEDIA"))


```

# Curva ROC e AUC
```{r}
library(pROC)
aucdt <- roc(dtFit$trainingData$.outcome, preddt[,2])
plot.roc(aucdt, print.auc=TRUE, print.thres = T, auc.polygon=TRUE,
         auc.polygon.col="#E47C3D", 
         ylab = "Sensibilidade", xlab = "Especificidade",
         main = "Curva ROC")
```

